### ISSUE TITLE
Crafttweaker integration does not appear to work

### ISSUE THREAD

**Issue by RedRaspberry** [Pikabyte/Immersive_Magneticraft_1.12#1]
I assume this is because the modid was not changed to reflect the new class names, for example:
`@ZenClass("mods.magneticraft.CrushingTable")`
I know it's not an issue with my scripts because they worked with the original MGC fork that silfryi wrote. I already tried changing the modid in those scripts to magnetic-engineering and that gave multiple errors (no such member, could not find, etc)

**Comment by Pikabyte** [comment]
I was worried something like this might happen. I hadn't tested CraftTweaker support since I couldn't find documentation on such a thing existing in the first place. I'll see if there's anything I can do. Hopefully it's written in Magneticraft and not in ModTweaker otherwise I'll need to rewrite the whole thing.

**Comment by Pikabyte** [comment]
Ah, I see it. It should be an easy fix. I'll have an update put out asap.

**Comment by Pikabyte** [comment]
oh no, it's breaking because i have a dash in the modid, which crafttweaker thinks is a minus and doesn't understand...i'm gonna have to change the modid of everything...again...alright this is gonna take a bit longer than I thought. I'll fix it by the end of tomorrow, but the modid is gonna need to change.

**Comment by RedRaspberry** [comment]
That's unfortunate! weird that CT doesn't have support for hyphenated modids, but thank you so much for taking the time to work on a fix

**Comment by Pikabyte** [comment]
Sorry I'm late, but I fixed it. It'll be uploaded to CF shortly.
